import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.scss';
import { motion, AnimatePresence } from "framer-motion"
const Home = () => {
  
  const arrayImage = [
    {id:1,name:"mare"},
    {id:2,name:"mare-sole"},
    {id:3,name:"fiume"}];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create transition page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Page transition
        </h1>
        <div className={styles["slider"]}>
          {
            arrayImage.map(({id,name})=> (
              <Link href={name} key={id} >
              <a key={id} className={styles["sunset"]}>
                <AnimatePresence>
                <motion.img
                  layoutId={name}
                  className={styles["sunset__image"]}
                  key={id} 
                  src={"./assets/"+name+".jpg"}
                  animate={{scale:1}}
                  whileHover={{scale:1.2}} />
                </AnimatePresence>

              </a>
              </Link>
            ))}
        </div>
      </main>

      <footer className={styles.footer}>
        studio - test
      </footer>
    </div>
  )
}
export default Home;